### ISSUE TITLE
Photos + infos : comment qu'on fait ?

### ISSUE THREAD

**Issue by ghost** [insaAEDI/aedi-reborn#2]
Il va falloir changer tout le contenu, en particulier les noms et les photos.

Comment s'organise-t-on pour récupérer tout ce bazar ? Un drive, une dropbox, une autre alternative ?

---

La question de la collaboration reste ouverte. Si on ouvre le projet à plus de gens, comment on gère ça ? 

Loïc a proposé une branche `prod`, ce qui semble assez logique. Y a moyen de limiter l'accès des gens à certaines branches, ou bien ça marche à la confiance ?

**Comment by LoicTouzard** [comment]
J'ai l'impression d'avoir déjà vu ça quelque part ...

**Comment by ghost** [comment]
Bon, ou bien t'façon c'est Hugues le photographe, donc on gère. Hugues, t'es beau.
