### ISSUE TITLE
Framework ? #leChangementCestMaintenant

### ISSUE THREAD

**Issue by ghost** [insaAEDI/aedi-reborn#3]
## Le concept

Comme de toute façon faut changer à peu près tout le contenu du site, et que c'est globalement un chouïa le bazar vu que y a plusieurs générations qui ont bossé dessus manifestement sans communiquer d'une fois sur l'autre, et que de toute façon il est vieux, il serait p't'être temps de faire un vrai truc. Genre avec un bon gros framework des familles.

Parce que comme ça, ça sera :
- Cool
- facile à récupérer par les suivants parce que mieux organisé
- globalement plus simple à éditer, parce qu'écrire des pages html c'est _has been_
- chais pas, ça peut être instructif aussi.
## Le problème

Ben, des frameworks, y en a genre beaucoup. Et dans plusieurs langages, même. 
## La question

Quoi qu'on fait ? Si (framework != connerie), reste à en choisir un. Rester en PHP avec des trucs comme Symphony, ou n'importe quoi d'autre parce que y en a plein ?

_J'avoue être tenté par Django, parce que je suis tombé amoureux de Python._

**Comment by hverlin** [comment]
Si tu veux découvrir autre chose regarde Node.js :) (Framework type express, ou sails js (plus haut niveau))

**Comment by ghost** [comment]
Oui, je connais déjà Node.js, c'est bourrin ! :D
Et en plus c'est JavaScript, que je :heart: aussi.

J'avoue que [Sails.js](http://sailsjs.org/) est aussi vachement haut dans mon classement.

**Comment by LoicTouzard** [comment]
Ha la la ...  @hverlin toujours autant partisant du JS ! ^^
Pour ma part je connais les framework Symfony2 et Django, je serais donc plus partant pour ceux là :P

**Comment by ghost** [comment]
@LoicTouzard Je sais bien, c'est pour ça que je demande :D
Si on regarde [ce comparatif](http://vschart.com/compare/sails-js/vs/django-framework), y a rien qui ressort vraiment pour départager Django et Sails.js. Tout ce que j'ai noté, c'est :
- plus de mémoire utilisée par Sails.js, mais 1GB ça reste mineur si je ne m'abuse (8x plus que 128 MB quand même)
- éditeur WYSIWYG sous Django, sauf que bon, c'est facile d'en rajouter dans un projet Node.js. C'est juste pas intégré de base dans Sails.js, mais c'est un faux argument

Globalement, Django a pour l'instant une plus grosse communauté, mais évidemment c'est susceptible de bouger, vu que Node.js est vachement en pleine expansion et est quand même über-cool. Mais Python c'est badass aussi. Et surtout, Node.js est justement en plein développement (v0.12.7), donc tout n'est pas vraiment fini (même si ça reste cool, et de plus en plus chaque jour).

**Comment by hverlin** [comment]
ouais mais Node pour un serveur, c'est pas mal ! :)

---

 (et pas besoin d'autant de mémoire hein ^^, 256 Mo suffisent je pense, enfin sur des VM avec 512 Mo ça tourne très bien)

**Comment by ghost** [comment]
'fin, l'argument "Node pour un serveur, c'est pas mal" est assez limité, on peut dire la même chose avec pas mal de trucs. Genre Python xD

**Comment by ghost** [comment]
Bon, en tous les cas, on va tomber sur un autre souci. A savoir que Centos 5, c'est vraiment BEAUCOUP trop stable, et que dans les repos y a ni node, ni django, et que leur gcc est trop vieux pour les compiler. Ça m'soûle :/

**Comment by ghost** [comment]
Et bon, je suis plutôt chaud pour faire une full réinstall du serveur, mais en ssh c'est chaud. Je pense que vu que je rentrerai tôt à Lyon, j'irai voir avec la DSI.
(j'ai plein d'idées de distros, par exemple SparkLinux ça claque et c'est facile à utiliser. 'fin, plus que Arch quoi)

**Comment by ghost** [comment]
OU BIEN, juste un truc simple comme AngularJS. A voir, je vais essayer pour m'amuser :p

**Comment by hverlin** [comment]
bah si tu as que du front à faire ça va aussi bien :)

**Comment by ghost** [comment]
Je pense que je vais faire vite fait avec Angular, histoire de bien réorganiser tout en pouvant déployer dans la config actuelle du serveur.

Comme ça, quand viendra le moment du vrai gros changement, ça sera plus simple. Et je pense vraiment qu'on doit le faire aussi vite que possible, parce que j'assumerai vraiment pas de passer un système aussi bordélique aux prochains. Le support de Centos 5.11 s'arrête en 2017, les repos ont à peu près 8 ans de retard (si, si, GCC 4.2 c'est 2007 et on l'a pas :/ ), et j'ai même pas réussi à changer la config http correctement, je fais une redirection du coup.

**Comment by ghost** [comment]
Du coup, pour l'instant Flight, la question se posera peut-être de nouveau si/quand grosse MaJ du serveur.
