### ISSUE TITLE
On ne peux plus voir les emails sur la page de contact

### ISSUE THREAD

**Issue by hverlin** [insaAEDI/aedi-reborn#5]
http://aedi.insa-lyon.fr/contact#

On peut plus voir les emails ! :)

**Comment by ghost** [comment]
Oui, je sais ^^
Faut retrouver le javascript.

**Comment by ghost** [comment]
```
// E-NoBot - Fonction expérimentale de protection des emails contre les bots spammeurs :
$(document).ready(function() {
    $('.e-noBot').click( function() {
        $('.e-noBot').each( function(index) {
            var em = $(this).attr('e-name')+String.fromCharCode(64)+$(this).attr('e-domain');
            $(this).attr('href', 'ma'+'ilt'+'o:'+em);
            $(this).html(em);
        });
        $('.e-noBot').removeClass('btn-mini btn btn-info');
        $('.e-noBot').unbind('click');
        return false;
    });
});
```

Mais bon, est-ce vraiment nécessaire ?

Bon, et surtout, les 4 boutons pareils qui s'enlèvent tous en même temps ça fait un peu dégueu. Je suis pas sûr que c'était l'idée à la base :D

**Comment by ghost** [comment]
En tout cas, j'ai une idée pour balancer le javascript proprement sur toutes les pages, faut juste que je trouve comment faire exactement.

Genre une petite boucle dans le layout, qui écrit le code, et qui prend en argument un tableau de fichiers, géré par Flight du coup.

**Comment by hverlin** [comment]
Je suppose que tu as juste à mettre un lien vers ce code dans le layout

**Comment by ghost** [comment]
nan, mais tant qu'un faire, un truc plus global. 'fin c'est pt'être pas nécessaire.

**Comment by ghost** [comment]
Surtout, je pense que système anti-bots en particulier est inutile. C'est moche, et les mails sont hardcodés dans la page de toute façon ; si je suis un bot, je m'embête pas à séparer ce qui est dans les balises et ce qui n'y est pas, je prends tout et je choppe tous les mails que je peux trouver.

Donc je propose de tout mettre en clair x)

**Comment by hverlin** [comment]
sinon il y a une technique pas trop mal qui consiste à inverser l'email  en CSS 
http://bavotasan.com/2009/a-clever-and-safe-way-to-display-your-email-address/

Je mets ça en attendant  et je le mets `user-select: none` sinon on copie l'adresse à l'envers

**Comment by hverlin** [comment]
je le mets user-select: none; sinon on copie l'adresse à l'envers

**Comment by ghost** [comment]
Ah, ben voilà, ça c'est une vraie technique. Je r'garde. Merci !

**Comment by hverlin** [comment]
Du coup, c'était quoi les anciens emails ? ^^ 
Histoire qu'on puisse enlever cette issue ?

**Comment by ghost** [comment]
Heuuu, là chez moi ça fait "moc.liamg@idea", c'est normal ? :D

**Comment by hverlin** [comment]
Où ça ? Dans le html ? C'est normal il faut l'écrire à l'envers et le CSS
le remet dans le bon sens ! :)

**Comment by ghost** [comment]
Non, sur la page dans le navigateur je veux dire. J'ai testé Chrome et Firefox, c'est à l'envers xD

**Comment by ghost** [comment]
Ou bien j'ai mal fait la maj sur le serveur, vu qu'en local ça marche. Je mets les bonnes adresses et je résous le problème :D

**Comment by hverlin** [comment]
Pas de soucis avec mon téléphone en tout cas

**Comment by ghost** [comment]
Compris, c'était le cache du navigateur qui faisait le vilain.

**Comment by ghost** [comment]
En revanche, je ne suis pas fan du fait que ça ne soit pas copiable, je réfléchis à une solution. Le seul problème, c'est que JS n'a apparemment pas accès au presse-papier.

EDIT : peut être du JS pour vraiment inverser le texte au clic, tout en virant l'inversion CSS. ça devrait marcher. (et en plus on pourra virer toute la partie avec des vilains préfixes que j'aime pas)

**Comment by ghost** [comment]
Et voilà !
